### ISSUE TITLE
Token copies of permanents with in-set art variants do not have any image assigned

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10094]
When copying a permanent, either while on the stack or on the battlefield, the token created will only appear with an image if the copied card has no art variants in its set. 

Tests done (using a [[Helm of the Host]] for all copying):
• Copied an [Abyssal Persecutor from WWK](https://scryfall.com/card/wwk/47/abyssal-persecutor), which has been printed multiple times but has no variations in the set. Outcome was as expected, with tokens being assigned the correct image.
• Copied a [Dream Devourer from KHM](https://scryfall.com/card/khm/90/dream-devourer), which has only ever been printed in that set and has art variations within the set. Outcome was all copies of Dream Devourer **not** appearing with an image.
• Copied a [Zask, Skittering Swarmlord from J22](https://scryfall.com/card/j22/47/zask-skittering-swarmlord), which has only ever been printed in that set and has no art variations in the set. Outcome was as expected, with tokens being assigned the correct image.
• Copied a [Gravecrawler from **2X2**](https://scryfall.com/card/2x2/78/gravecrawler), which has been printed multiple times and has art variations within the set. Outcome was all copies of Gravecrawler **not** appearing with an image.
• Copied a [Gravecrawler from J22](https://scryfall.com/card/j22/423/gravecrawler), which has been printed multiple times but has no variations in the set. Outcome was as expected, with tokens being assigned the correct image.

Based on the above tests it can be concluded that the common issue is cards with art variants within their set being handled incorrectly when tokens are being assigned images, resulting in placeholders. Visual outcome of all above tests can be seen below:
![token-copy-tests](https://user-images.githubusercontent.com/26198472/222912398-3bb0e842-ce0a-492c-b4cd-b4d8af3b3f9e.PNG)

**Comment by sprangg** [comment]
Might be a similar case to the double-faced cards with art variants, which I fixed here https://github.com/magefree/mage/pull/9826

**Comment by JayDi85** [comment]
Must be fixed in changes from #10139

**Comment by PurpleCrowbar** [comment]
This issue persists. Not sure if this is a regression or if it was never resolved by changes made in regards to #10139

**Comment by PurpleCrowbar** [comment]
Some discoveries in regards to this issue and permanents which enter as copies of other permanents. Note that [[Clone]] has no art variants in the set M14, and that [[Glasspool Mimic]] *does* have an art variant in the set ZNR. When Clone enters as a copy of [[Runeclaw Bear]], from the set M15 (no art variants), it is correctly assigned the image of the bear. When GM enters as a copy of the same Runeclaw bear, it has no image assigned. Furthermore, when Clone enters as a copy of [[Intellect Devourer]], from the set CLB (*has* got an art variant), it is *not* assigned an image. However, when GM enters as a copy of Intellect Devourer, it *does* have the image assigned.

Finally, I decided to test with [[Phyrexian Obliterator]] from the set ONE (which has 3 art variants, so 4 total arts), and this yielded unexpected results. The Glasspool Mimic, which has art variants, was able to successfully inherit the art of whichever Obliterator it copied. The Clone, which does *not* have art variants, *did* enter with art (unlike in the case of it copying something with only one other art variant), but it did not seem to inherit the art from the permanent being copied, instead just picking the "first" art for the card (I suppose the first art that appears in the database?) See a table compiling these results below:
![image](https://github.com/magefree/mage/assets/26198472/53bd418b-b8bc-4eaa-acde-4dcad88df441)
Green = correctly inherited art from copied permanent
Red = no image assigned
Yellow = an image was assigned, but specific variant not correctly inherited from copied permanent

**Comment by Grath** [comment]
In my experience, token copies are much more successful at having art but non-token copies (clone and the like) are less likely to successfully have art assigned after these changes.

**Comment by PurpleCrowbar** [comment]
Development on this thanks to changes made in 34816be implementing the missing image hint in tooltips. Shown in image below is a token copy of [[Jon Irenicus, Shattered One]], a card with multiple in-set art variants.
![image](https://github.com/magefree/mage/assets/26198472/8152e6aa-5ed3-4e0d-b9ae-11ea9ea261a1)
Predictably, the image of the copied permanent is not inherited in the copy. However, the hint appears to imply that XMage tries to search for an appropriate image for the card in the set's token folder, which presumably would never contains an appropriate image for a non-token card.

This does not explain the findings in [my comment above](https://github.com/magefree/mage/issues/10094#issuecomment-1811202859). Assuming the problem is that XMage is wrongly searching sets' token image folders for images to apply to token *copies* (which, as stated, wouldn't have appropriate images in such folders), it doesn't make much sense to me that the number of art variants the copier and copied permanent have is relevant to whether or not the permanent has the correct art applied. This implies that the hint is potentially inaccurate, or that my comment above is outdated.

**Comment by PurpleCrowbar** [comment]
@JayDi85 Is this fixed now? In the [update notes for the latest beta release](https://jaydi85.github.io/xmage-web-news/news.html) it seems like you describe this issue as being resolved:

> cards: fixed miss token image in some use cases (if it was created from a card and a set contains multiple images);

**Comment by JayDi85** [comment]
Yes, it must be fixed by 0e39d6a8334532efa4f4fd889c8c41d51377419c
