### ISSUE TITLE
Janjeet Sentry causes unplayable bug

### ISSUE THREAD

**Issue by twogk** [magefree/mage#2331]
![card](https://cloud.githubusercontent.com/assets/22122576/18623158/f0c37d60-7dee-11e6-9efd-bb540fed1d51.gif)
![janeet sentry](https://cloud.githubusercontent.com/assets/22122576/18623162/f910ad44-7dee-11e6-8836-112a48a1259c.gif)

**Comment by LevelX2** [comment]
Fixed with 1.4.15v4

**Comment by brodee** [comment]
I think that there are still problems.  I have the latest code and I still see problems.

it causes server side errors:
Exception in thread "CALL main-67" java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at mage.server.ChatManager.leaveChat(ChatManager.java:75)
at mage.server.MageServerImpl$14.execute(MageServerImpl.java:562)
at mage.server.MageServerImpl$53.run(MageServerImpl.java:1177)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

and the client reports:
WARN 2016-09-20 21:54:41,409 message out of sequence - ignoringMessageId = 29 method = gameInform =>[AWT-EventQueue-0] CallbackClientImpl$1.run 
FATAL 2016-09-20 21:54:46,820 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,822 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,823 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,823 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,824 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,830 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,834 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
..... infinite loop
