### ISSUE TITLE
Nest of Scarabs does not produce tokens when -1/-1 counters are placed on creatures.

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3174]
Nest of Scarabs does not produce tokens when -1/-1 counters are placed on creatures.

- from forums

**Comment by jeffwadsworth** [comment]
This one is curious.  First time I tested it (code looked fine), it did in fact fail to trigger.  I put in some simple test code (no change to the actual functionality) and it worked.  Can anyone else verify?

**Comment by HanClinto** [comment]
I just tested it and it seemed to work fine for me (though I couldn't get Scarabs to trigger in the first game that I ran).  I never saw it mess up.

**Comment by LevelX2** [comment]
Fixed with 86bc78e4b88422da994a426f7634d28316b267df.

**Comment by C4R5TEN** [comment]
Still does not work for me
![no_scarab_token](https://cloud.githubusercontent.com/assets/28264140/25585208/bfc6cfc6-2e99-11e7-9201-7381a2fab51f.JPG)

**Comment by RMcD94** [comment]
Can verify this also http://i.imgur.com/MTZa5nq.jpg

**Comment by drmDev** [comment]
unit test also demonstrating this is an issue referenced above. Do not close this out at the very least until the most basic unit test is passing. May also try adding more tests for different scenarios.

**Comment by DaMachinator** [comment]
I also have this issue. It appears that Nest of Scarabs did not trigger at all when putting -1/-1 counters on a creature with Channeler Initiate's ETB effect.
