### ISSUE TITLE
Patron of the Nezumi - Rat offering not working

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3550]
I wanted to cast Patron of the Nezumi and do Rat sacrifice but I doesn't Work!
I pressed yes for sacrifice.
Selected a rat with 1B (Kuro's taken)
The cost stays 5BB

Rat offering should reduce the cost with 1B

Screenshot:
imgur.com/x3qXwZL
-- from forums

**Comment by ingmargoudt** [comment]
making a test for this

**Comment by ingmargoudt** [comment]
The unit test for this could not reproduce this, I tested both offering a rat, and not offering a rat, and both times the mana cost was correct

**Comment by Zzooouhh** [comment]
I'm experiencing this same bug with Patron of the Moon - after offering a Soratami Savant with Sapphire Medallion in play, it asks me to pay {4}{U}{U}.

**Comment by Rezarious** [comment]
Tried to do the same, but with Locust Miser. The difference should have been {3}, and I had 3 floating black to cast it, but it demanded the full {5}{B}{B} instead.

Good to know this has been an issue since 13 months ago merely resolved with "works on my machine"
¯\_(ツ)_/¯

**Comment by LevelX2** [comment]
@isGordon 
It's not easy to reproduce so any hint was was special as the problem occured can help. Can you provide game log or hardcopy of the game?

How did you bring the Locust Miser in play. By regular casting?

I tested with Anafenza, the Foremost for opponent in game so the sacrificed rat goes to exile instead of graveyard. This didn't produce a problem.

**Comment by waffledoctor87** [comment]
Confirming that Patron of the Orochi still doesn't reduce when sacrificing from Command Zone 

tested with Lotus Cobra and Matsu Tribe Sniper, should cost 5G not 6GG

**Comment by Zerrisx** [comment]
Looks like this is just a command zone issue; marking as a duplicate of that one.

Duplicate of #4909
