### ISSUE TITLE
Game freezes on disconnected player's commander dying

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4262]
This is related to the more general issue of disconnected (not conceded!) players' permanents persisting on the battlefield which I'm sure was reported here at least once before. Just for clarity's sake: If a player loses connection, his board "folds in" like during a game loss, but the permanents are still there and interact with other players/permanents as normal. A Null Rod owned by a disconnected player still shuts down activated abilities of artifacts, etc.

Arguably the most commonly seen and egregious part of this issue however happens in EDH games: if such a player has his commander persist on the board this way and the commander gets killed somehow after the disconnect happens (typically by a Wrath of God effect), the game lingers on forever as it waits for the now-unavailable player to make the decision to move the commander to the command zone. Since the whole disconnect-persist issue is most certainly a complex matter to solve, I'd love to see at least this part sorted out for now - perhaps there could be a new "player.choose" method for commander zone-changing that has a built-in time limit?

**Comment by JayDi85** [comment]
If user disconnected then he can reconnect and resume game. There are must be timeout for every user's interaction.

**Comment by Zzooouhh** [comment]
Sometimes the user can reconnect and proceed with his normal actions, true. But other times, his board just folds down in a similar way as when a player concedes or dies, except you can see a tiny sliver of a scrollbar just right of his picture and stats table (life, library etc.) - if the user reconnects afterwards, he is always forced into spectator mode. Haven't quite noticed any specific cause why and when this happens.

**Comment by derlhurgoyf** [comment]
I've seen above behaviour also for players who conceded the game. Even then the permanents wouldn't disappear. Strangely enough in one game with Omen Machine, nobody could draw cards, but it also wouldn't trigger during draw to play the top card. 
This is somewhat serious, as in the last week I haven't been able to complete ANY multiplayer match.

**Comment by JayDi85** [comment]
Freeze on player's concede was fixed on next v3 release.

**Comment by LevelX2** [comment]
Fixed a bug now, that the commander in the command zone was not removed from the game, if a player left a multiplayer commander game. Maybe this caused a part of the problems.

**Comment by Zzooouhh** [comment]
As of Xmage 1.4.30V6 this issue still persists. Just had an opponent's Brago commander stick around in a 4 man EDH game after he got disconnected.

**Comment by Zerrisx** [comment]
Possibly related issue:

#4413

**Comment by JayDi85** [comment]
Possible reason: disconnected user connected to server but miss game start event due to bad connection (e.g. he can't see game window, try to play another game and server can't remove it from old game -- cause it active). Another possible reason: player ignore the game.

Possible solution: add active/disconnected status per game (ping or last active), not per server. Bonus: xmage can drop players who ignore the game (no need to wait 20 mins timer out).
