### ISSUE TITLE
Cowardice not working BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4465]
The blue enchantment Cowardice does not seem to work when opponents target opponents creatures with any spell or ability. I don't know if it works on the owners' own creatures for spells (specifically just spells) they control (as the game ended before this could occur), but i played a game where a Big Game hunter targeted an indestructible Rhonas the Indomitable and nothing happened (Rhonas the Indomitable's ability was not bouncing his own creatures either).

**Comment by JayDi85** [comment]
Fixed via #4726

**Comment by tcontis** [comment]
This was not fixed. i mistakenly thought I had, but didn't have an idea what I was doing. I have not yet.
