### ISSUE TITLE
Skip keys like (F5, F9, F11 ...) skip sometimes one step too far.

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4470]
In various multiplayer matches I noticed that during my first turn, if I'm not the starting player and just hit F9 to wait until my turn it would skip right to my end of turn and have me discard.
With F11 it will skip to my main phase instead of the end of turn of the player before me.

This is only the first turn though, others are fine.

**Comment by Zzooouhh** [comment]
Recently I've also noticed F5 glitching out and acting like F9 instead.

**Comment by spjspj** [comment]
I believe this was fixed in 1.4.27v2 with the rollbacks from the Skip logic.

**Comment by JayDi85** [comment]
[From reddit](https://www.reddit.com/r/XMage/comments/7vd67w/can_we_get_block_to_work_again/):

F9 skips block now out of now where. That along with the switched attack/pass button really infuriate me.

**Comment by Sankluj** [comment]
Hi! I can confirm that the issue is still here in 1.4.27v2 but it doesn't always happen during my first turn.

I noticed two behaviours:
* Skipping to end of opponent turn skips to my first main step and sometimes ignore blocking phase
* Skipping opponent turn sometimes skips my turn.

Hope this can be fixed :)
Good luck!

**Comment by LevelX2** [comment]
I can't reproduce this. 
Probably there is something done or something happens during the turn what causes the skipping.

**Comment by derlhurgoyf** [comment]
I noticed it to be more frequent in multiplayer games if I'm not the starting or 2nd player.

**Comment by derlhurgoyf** [comment]
This seems to have gone away with 1.4.27V3
