### ISSUE TITLE
Premodern as a format

### ISSUE THREAD

**Issue by skiztik** [magefree/mage#5301]
http://premodernmagic.com/rules#rules
there's a tiny thread on this on the xmage subreddit, but I'm opening this here so the developers see it, in case they missed that one.

We would really like this format added to xmage in addition to all the other great formats it already supports.

thanks!

**Comment by JayDi85** [comment]
@jmharmon started to implement it in #5300 (or another PR).

**Comment by skiztik** [comment]
it looks as if this was added, but as it was part of a different request, it was pulled (with the recommendation that it be added as its own request, but that was never done).  @jmharmon if you would be so kind as to add that java file to a new PR the premodern players would really appreciate it!

**Comment by JayDi85** [comment]
@skiztik xmage already have that format, Wait next update (32).

![shot_181207_145509](https://user-images.githubusercontent.com/8344157/49643816-23280680-fa30-11e8-9cec-00c9c0cdd848.png)

**Comment by rpgdude** [comment]
When will this be released? The Premodern option is still not available in the dropdown.

**Comment by JayDi85** [comment]
Fixed it. De-server already have it... beta-server was updated today... others servers must update it later (you can help if find other server admins and send that topic link to them).

Server's config files must be updated (adds that new lines to `config.xml` file):
* New deck type:
  * `<deckType name="Constructed - Premodern" jar="mage-deck-constructed-1.4.33.jar" className="mage.deck.Premodern"/>`
* New cubes:
  * `<draftCube name="MTGO Vintage Cube December 2018" jar="mage-tournament-booster-draft-1.4.33.jar" className="mage.tournament.cubes.VintageCubeDecember2018"/>`
  * `<draftCube name="SCG Con Cube 2018 December" jar="mage-tournament-booster-draft-1.4.33.jar" className="mage.tournament.cubes.ScgConCube2018December"/>`

**Comment by rpgdude** [comment]
> Fixed it. De-server already have it... beta-server was updated today... others servers must update it later (you can help if find other server admins and send that topic link to them).
> 
> Server's config files must be updated (adds that new lines to `config.xml` file):
> 
> * New deck type:
>   
>   * `<deckType name="Constructed - Premodern" jar="mage-deck-constructed-1.4.33.jar" className="mage.deck.Premodern"/>`
> * New cubes:
>   
>   * `<draftCube name="MTGO Vintage Cube December 2018" jar="mage-tournament-booster-draft-1.4.33.jar" className="mage.tournament.cubes.VintageCubeDecember2018"/>`
>   * `<draftCube name="SCG Con Cube 2018 December" jar="mage-tournament-booster-draft-1.4.33.jar" className="mage.tournament.cubes.ScgConCube2018December"/>`

@JayDi85 I can confirm that Premodern is available as an option on the beta server.
However, the option is still not available on the DE server. Please update the DE server in the same way as the beta server.

Thank you!

**Comment by JayDi85** [comment]
de will be available after next restart

**Comment by rpgdude** [comment]
@JayDi85 Just tried this out this morning. There appears to be a bug in the format support.
The program does not accept Exodus as a legal set. Exodus is a legal set in Premodern.
Please add support for this set to the format.

Thank you!

**Comment by JayDi85** [comment]
@rpgdude thanks for report, it's will be updated with next release (in that friday).

P.S. All xmage's premodern sets and banned list [available by that link](https://github.com/magefree/mage/blob/7eb1ccfebd84952c8ec3f30f4ca1d5f56b618fea/Mage.Server.Plugins/Mage.Deck.Constructed/src/mage/deck/Premodern.java).

**Comment by rpgdude** [comment]
@JayDi85 Looks like there is another issue. Premodern games don't show up in the Tables view.
I think that visibility of the hosted Premodern tables should be controlled by the Other filter in a similar way to Freeform games. Because of this bug, there is no way to join a Premodern table.

**Comment by JayDi85** [comment]
@rpgdude i've fixed it -- all users can downloads it by launcher (33v3a version). Restart launcher to see new update.
