### ISSUE TITLE
Shark typhoon problem 

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#6450]
When casting a spell the shark token instantly dies no mater what

**Comment by DominusMaximus** [comment]
This happened to me as well. The trigger seems to be creating 0/0 sharks regardless of the noncreature spell's converted mana cost.

**Comment by LevelX2** [comment]
Fixed with 365754b6f746eeddf93f2d53730c01026d48c242.

**Comment by Dragas** [comment]
The issue still seems to be present, but in a weird way. If a spell gets removed from the stack (via commit, or a counter spell), XMage creates a 0/0 token instead.

**Comment by JayDi85** [comment]
@Dragas what version are you trying? That's fix available on beta server/client only.

**Comment by Dragas** [comment]
1.4.43V0 (2020-06-20)
