### ISSUE TITLE
It's possible to get snow lands when adding random lands to a limited deck

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#7222]
It's possible to get snow lands when adding random lands to a limited deck with the <Random lands> that pulls from any set. This can, for example, mess up drafts where you're supposed to get the snow lands by drafting them.

When adding random lands, could it be checked that their name or type doesn't include snow?

**Comment by JayDi85** [comment]
Are you talking about "add lands dialog" in deck editor?

**Comment by sprangg** [comment]
Yes, by selecting <Random lands> it's possible to get the snow lands. Image: https://imgur.com/a/YDHqYjy

Around here is where I think it might be good to add the type/name check for "snow". https://github.com/magefree/mage/blob/ed6bd4d7a7e5e1d4dccb5e59a098427ba0324372/Mage.Client/src/main/java/mage/client/dialog/AddLandDialog.java#L152

Previously a similar (worse) issue was fixed where snow lands could be added easily to draft decks. Oh and looks like it was fixed by you! Thanks for that one. https://github.com/magefree/mage/issues/5831

**Comment by JayDi85** [comment]
Fixed by dd7c1939d3b1fd649f3cf841cc1cebb23291a36a

**Comment by sprangg** [comment]
This bug is still happening. It can be replicated by doing a draft with bots (tested with both Kaldheim and Ultimate Masters, happens with both).

Click through the draft, then add lands from the lands-menu and select "Random lands" as their set. Add 50+ lands and some will be snow-covered if you have the "Only full art lands" checkbox enabled. If you don't have it enabled, it's also possible to get snow-covered lands but the chance is lower.
