### ISSUE TITLE
[KHM] Prismatic Bridge upkeep trigger is duplicated

### ISSUE THREAD

**Issue by dosfod** [magefree/mage#7501]
Hi, 

the Prismatic Bridge trigger seems to be bugged, because is doubled without any card on the battlefield that has that effect as shown in the screenshot:

![image](https://user-images.githubusercontent.com/29545637/106932892-9153db00-6718-11eb-994f-7c3f514ade54.png)

Please let me know if you need more information.

Thanks in advance, 

Kind regards.

**Comment by JayDi85** [comment]
Show game logs before and after that triggers.

**Comment by dosfod** [comment]
Hey, 

it is the same object:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/29545637/106940109-6d48c780-6721-11eb-99b4-e8681ed96dfd.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/29545637/106940201-8b162c80-6721-11eb-8558-b0167393da46.png">

Hope this helps.

Kind regards

**Comment by weirddan455** [comment]
Is Esika your commander?  Another user is reporting MDFCs double triggering in commander in #7503

**Comment by dosfod** [comment]
Yep, she is

**Comment by JayDi85** [comment]
Fixed by ac98a3a31ae96372302a71f9dc737ae5e4522c07

**Comment by dosfod** [comment]
Is this deployed at beta already? I noticed an update this morning, but the bug is still present :/

**Comment by JayDi85** [comment]
@dosfod nope, it will be with next beta update today (or maybe it will be release).
