### ISSUE TITLE
Gilded Drake has bad interaction with Kiki-Jiki copy effects

### ISSUE THREAD

**Issue by jumpinjackie** [magefree/mage#8742]
[Gilded Drake] does not behave as expected with the token copy ability of [Kiki-Jiki Mirror Breaker] or [Fable of the Mirror-Breaker // Reflection of Kiki-Jiki]

Case 1:

If Gilded Drake is in your control and you copy it with Kiki-Jiki Mirror Breaker.

 1. Token copy of Gilded Drake comes into play
 2. You get prompted for an opponent's creature to exchange
 3. The exchange is made.
 4. At end of turn the Gilded Drake token that's now under opponent's control *does not* get sacrified at the next end step.
 
Case 2:

If Gilded Drake is in your control and you copy it with Reflection of Kiki-Jiki:

 1. Token copy of Gilded Drake comes into play
 2. You get prompted for an opponent's creature to exchange
 3. The exchange is made.
 4. At end of turn the Gilded Drake token that's now under opponent's control *does* get sacrified at the next end step.
 5. On the opponent's next upkeep step, the creature I exchanged with Gilded Drake returns back to the opponent's control. Nothing in the rules text for Gilded Drake or the Kiki-Jiki copy effect state that this has to happen.
 
Since both Kiki-Jiki and its reflection carry the same oracle text for its token copying ability, one of these abilities is implemented incorrectly. Either the token Gilded Drake I made that is now under opponent's control should be sacrified at next end step or it doesn't. I'm not sure of the rulings on this.

An easy way to see this issue in action is to set up an AI freeform mirror match with the following 40 card deck:

8 Gilded Drake
8 Kiki-Jiki Mirror Breaker
8 Fable of the Mirror-Breaker // Reflection of Kiki-Jiki
16 Black Lotus

Eventually you'll enter a board state where you can see both cases in action

**Comment by Grath** [comment]
Case 1 is the correct interaction, that pull request should fix the problem in Case 2 step 4, and hopefully that will also address Case 2 step 5 happening? Otherwise I'm not certain what's happening there.

**Comment by Alex-Vasile** [comment]
The PR should handle step 4, I will take a closer look at step 5 to see what was causing that issue.

**Comment by Alex-Vasile** [comment]
Testing it further, Step 5 still occurs if the copy of gilded drake is killed.

**Comment by Alex-Vasile** [comment]
It occurs even if [[Guardian Beast]] is untapped and under your control when the Drake dies.

**Comment by Tharkon** [comment]
I want to add that this bug also appears when putting Gilded Drake into play using encore.
The drakes do get sacrificed even though they shouldn't since it is the player that activated encore that is instructed to make the sacrifice.
And the control effect is also gone when the next turn starts.
