### ISSUE TITLE
Delaying shield counter 

### ISSUE THREAD

**Issue by fleo13** [magefree/mage#965]
Only one counter is removed per turn whatever you pay with life or mana. 

Also, when use in conjuncture with Phyrexian Unlife, damage is still receive but you are not suppose to because you lose life, you are not taking damage.

**Comment by LevelX2** [comment]
The only one counter is removed bug is fixed beyond 1.4.1v3

**Comment by drmDev** [comment]
Is the interaction with Phyrexian Unlife still occurring? Will need to test later

**Comment by goesta** [comment]
I'll close this issue because it seems to be fixed.
