### ISSUE TITLE
Copying X-cost Permanent spells doesn't function correctly

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9697]
"[[Magus Lucea Kane]] Copies spell without x effect triggering properly: Ravenous did not trigger on the second spell, no counters attached, no card drawn.

Appears to work in the stack, but hits the battlefield without x count applying."
![unknown](https://user-images.githubusercontent.com/48962821/198765958-b7441850-4889-41f2-927f-0596a8fc9cbb.png)

**Comment by Reya87** [comment]
I confirm the bug. The delayed trigger of Lucea goes in the satck but Ravenous does not trigger and counters are not placed on the copied creature spell. 

I tried while casting a Zoanthrope and a Voracious Hydra.

**Comment by Reya87** [comment]
![Capture3](https://user-images.githubusercontent.com/90519360/198857507-84787098-fed6-4468-8b03-ae6f6baaea9b.PNG)
![Capture4](https://user-images.githubusercontent.com/90519360/198857509-ea5b1576-3ec4-4ab7-a8f2-04ce7de44fe5.PNG)

I tried to make screenshots of the issue. As we can see, Lucea Kane delayed trigger goes in the stack for casting Aberrant but at resolution, the copy enters the battlefield with 0 counter (if we look at the gamelog, it says that the copy of Abberant enters the battlefield but immediately goes to the graveyard. And Ravenous don't trigger for the copy).

**Comment by Reya87** [comment]
Magus Lucea Kane delayed trigger ability don't trigger with ability containing "X". I tried with Kessig Wolf Run.

**Comment by ldeluigi** [comment]
[[ Kessig Wolf Run ]]

**Comment by jeffwadsworth** [comment]
This occurs with permanent spells only.

**Comment by jeffwadsworth** [comment]
[[Lithoform Engine]] has the same issue with its 3rd activated ability.

**Comment by Grath** [comment]
I'm guessing this happens because the Token from a Copied Permanent Spell doesn't have the same ID as the Spell that created it. I'm not sure how to cleanly fix it.

**Comment by Reya87** [comment]
So it's the same issue as Lithoform Engine ? And maybe there is no way to fix it ?

**Comment by Grath** [comment]
> So it's the same issue as Lithoform Engine ?
Yes.

> And maybe there is no way to fix it ?
Digging further.

I've hacked the token code to where it's now correctly plumbing the copied permanent spell's UUID through to the token that actually enters the battlefield, but it's still not getting the X value ETB yet.

**Comment by Grath** [comment]
So, figured out the problem with EntersTheBattlefieldWithXCountersEffect via generous application of System.out.println (because IntelliJ refused to cooperate with doing debugger/breakpoint, for whatever reason):
- The token that's created by a copy of a spell has a different ID than the `spellAbility.getSourceId()` (which is `spell.card.getId()`)
- This can be fixed by changing `TokenImpl` to allow a static ID to be passed to `putOntoBattlefield`, and `PermanentToken` to allow a constructor with an ID which is passed up to `PermanentImpl`, so that the first token you create is given the `card.getId()` - but this is probably a terrible idea to have two objects with the same ID floating around; perhaps if there's a way to change the Spell and/or SpellAbility so that the Source is the token after it's been created?
- The following problem is that the `SpellAbility.getSourceObjectZoneChangeCounter()` is out of sync with the token's `getZoneChangeCounter()` so that the token's ZoneChangeCounter is one higher than the SpellAbility's source's ZCC. I tried getting it to change the SpellAbility's source's ZCC, but neither attempt (changing the card's ZCC or the spell.ability ZCC) worked; if I reduce the token's ZCC, that breaks permanent spell copies being kicked getting tracked correctly.
- None of this effort fixed `ManaSpentToCastWatcher` which means that neither Ravenous' card draw nor other X-cost ETBs are functioning correctly.

Still above my pay grade to fix, but there's some progress.

**Comment by Reya87** [comment]
Thanks for you effort. I hope it will give clue to fix it.

**Comment by JayDi85** [comment]
SourceId, ZCC and all other staff must be independent for original and copied permanents and cards. It's important feature. Each moving between zones must generates +1 ZCC (e.g. must creates a new object due mtg rules -- zcc is a tool to implement that rule).

**Comment by Grath** [comment]
I wasn't trying to pass the original permanent spell's ZCC/sourceID/etc from the original; the problem is that the connection to the X value gets lost in the transition from "spell copy on stack" to "token in play", and my theory was that making the resulting token have the same ID and/or ZCC as the spell that had been on the stack might have made it work, but it didn't fix the issue.

**Comment by Aycaramba100** [comment]
First I have to say, thanks guys! You do an amazing job!

Then my question, Is there a chance Lucea will get fixed in future updates?

**Comment by Grath** [comment]
You can click on the link just above your comment to follow the code change that should, in theory, fix this. You'll note that it says "Open" and not "Merged", which means that it hasn't yet been accepted.

**Comment by SmokinDice** [comment]
My post got deleted for beeing a duplicate, but one year later the issue is still the same, any fixes anytime soon?

**Comment by Susucre** [comment]
Your issue was closed, not deleted.
There has been heavy work from @ssk97 to fix that one along with other cost tracking bugs, but that is still at the PR stage.

**Comment by Reya87** [comment]
What is a PR Stage ?

**Comment by Susucre** [comment]
PR is short for Pull Request, so code has been proposed to be merged with the code base, but has not yet been fully approved. See https://github.com/magefree/mage/pull/10546 for the PR I mentioned above.

From my limited understanding of what is going on, the risk with the current PR is to degrade how much memory the server is using, and there is already crash due to memory issue in the beta server.
